### ISSUE TITLE
Heroku running into an issue using this buildpack

### ISSUE THREAD

**Issue by ghost** [diowa/rgeo-sinatra#4]
<img width="699" alt="Screen Shot 2022-06-06 at 2 57 19 PM" src="https://user-images.githubusercontent.com/71298382/172256052-571dad89-04fc-4638-af03-3735f38e00fa.png">

https://vesuvius.herokuapp.com/libraries/geos-3.10.2-heroku.tar.gz
Is this file still valid?

**Comment by tagliala** [comment]
Hi, I've updated GEOS to the latest 3.10.3

Unfortunately it is not possible to compile different versions of the same library because of timeout during deploys. Another option is to fork [Vesuvius](https://github.com/tagliala/vesuvius), change the library version, and deploy your own instance with an older version of the library

**Comment by ghost** [comment]
Awesome thank you, I realized soon after this post that the versioning was different. Gracias por su respuesta

**Comment by tagliala** [comment]
@henryzihaohuang just a heads-up: I've moved libraries to Heroku 22 stack and I've created another application for Heroku 20 stack at https://vesuvius-20.herokuapp.com/

I've also added a disclaimer to Vesuvius' readme to clarify that Vesuvius assets should not be used for production environments, since links and versions may change at any moment
